include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/**"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
