name: flutter_smarteam
description: SmartTeam smart project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.3
  intl: ^0.17.0
  sizer: ^2.0.13

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  golden_toolkit: ^0.10.0
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/images/

